### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by 9renpoto** [uncovertruth/auto-cookie#3]
## TODO

- [x] use webdriverio
   - [x] chrome or firefix, or both
- [x] **must** check cookie status

## how to local test

- use xip.io

```sh
lite-server &  // serve localhost:8000

wdio // run e2e tests to http://www.0.0.0.0.xip.io:8000 url
```

## Feature

- [x] use sauselabs

**Comment by taka-sho** [comment]
次はsauselabsの方をやっていきますか？
