### ISSUE TITLE
replace webdriverio

### ISSUE THREAD

**Issue by 9renpoto** [uncovertruth/auto-cookie#46]

**Comment by 9renpoto** [comment]
testcafe ?

**Comment by shoota** [comment]
I tried TestCafe. Unfortunately, TestCafe and its plugins are not provide Browser Object yet.
It can get detail cookie attributes, e.g, domain, path, that not get via `document.cookie` ,
http://webdriver.io/api/cookie/getCookie.html

**Comment by 9renpoto** [comment]
skip this issue 
because wdio wolecome back update
